---
- hosts: all
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that hello-world dir exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
    register: stat_result
  - name: Delete the hello-world dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://13.233.134.220:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.geekcap.vmturbo&a=hello-world-servlet-example&v=LATEST&p=war
       dest: /usr/share/tomcat/webapps/hello-world-servlet-example
  - name: Start Tomcat
    service: name=tomcat state=started
